version: '3'

services:
  overview:
    build: .
    volumes:
      - .:/src/app
      - /app/node_modules

    depends_on:
      - 'database'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production

  database:
    image: mongo:latest